# fly.toml app configuration file generated for htparticle on 2023-06-25T14:33:34+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "htparticle"
primary_region = "lhr"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
